use_frameworks!

platform :ios, '10.0'

target 'JUNFloatControl_Example' do
  pod 'JUNFloatControl', :path => '../'
  pod 'JUNFlex'

  target 'JUNFloatControl_Tests' do
    inherit! :search_paths

    
  end
end
